// import { icons } from "./icons";
//
// export const tabs: AppTab[] = [
//     { name: "index", title: "Home", icon: icons.home },
//     { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
//     { name: "insights", title: "Insights", icon: icons.activity },
//     { name: "settings", title: "Settings", icon: icons.setting },
// ];
//
// export const HOME_USER = {
//     name: "Khairul | Technical Support Engineer",
// };
//
// export const HOME_BALANCE = {
//     amount: 2489.48,
//     nextRenewalDate: "2026-03-18T09:00:00.000Z",
// };
//
// export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
//     {
//         id: "spotify",
//         icon: icons.spotify,
//         name: "Spotify",
//         price: 5.99,
//         currency: "USD",
//         daysLeft: 2,
//     },
//     {
//         id: "notion",
//         icon: icons.notion,
//         name: "Notion",
//         price: 12.0,
//         currency: "USD",
//         daysLeft: 4,
//     },
//     {
//         id: "figma",
//         icon: icons.figma,
//         name: "Figma",
//         price: 15.0,
//         currency: "USD",
//         daysLeft: 6,
//     },
// ];
//
// export const HOME_SUBSCRIPTIONS: Subscription[] = [
//     {
//         id: "adobe-creative-cloud",
//         icon: icons.adobe,
//         name: "Adobe Creative Cloud",
//         plan: "Teams Plan",
//         category: "Design",
//         paymentMethod: "Visa ending in 8530",
//         status: "active",
//         startDate: "2025-03-20T10:00:00.000Z",
//         price: 77.49,
//         currency: "USD",
//         billing: "Monthly",
//         renewalDate: "2026-03-20T10:00:00.000Z",
//         color: "#f5c542",
//     },
//     {
//         id: "github-pro",
//         icon: icons.github,
//         name: "GitHub Pro",
//         plan: "Developer",
//         category: "Developer Tools",
//         paymentMethod: "Mastercard ending in 2408",
//         status: "active",
//         startDate: "2024-11-24T10:00:00.000Z",
//         price: 9.99,
//         currency: "USD",
//         billing: "Monthly",
//         renewalDate: "2026-03-24T10:00:00.000Z",
//         color: "#e8def8",
//     },
//     {
//         id: "claude-pro",
//         icon: icons.claude,
//         name: "Claude Pro",
//         plan: "Pro Plan",
//         category: "AI Tools",
//         paymentMethod: "Amex ending in 1010",
//         status: "paused",
//         startDate: "2025-06-27T10:00:00.000Z",
//         price: 20.0,
//         currency: "USD",
//         billing: "Monthly",
//         renewalDate: "2026-03-27T10:00:00.000Z",
//         color: "#b8d4e3",
//     },
//     {
//         id: "canva-pro",
//         icon: icons.canva,
//         name: "Canva Pro",
//         plan: "Yearly Access",
//         category: "Design",
//         paymentMethod: "Visa ending in 7784",
//         status: "cancelled",
//         startDate: "2024-04-02T10:00:00.000Z",
//         price: 119.99,
//         currency: "USD",
//         billing: "Yearly",
//         renewalDate: "2026-04-02T10:00:00.000Z",
//         color: "#b8e8d0",
//     },
// ];



import { icons } from "./icons";

export const tabs: AppTab[] = [
    { name: "index", title: "Home", icon: icons.home },
    { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
    { name: "insights", title: "Insights", icon: icons.activity },
    { name: "settings", title: "Settings", icon: icons.setting },
];

export const HOME_USER = {
    name: "Khairul | Technical Support Engineer",
};

// Total calculated from your list: 7232
export const HOME_BALANCE = {
    amount: 7232.00,
    nextRenewalDate: "2026-05-25T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "tnb",
        icon: icons.activity,
        name: "TNB Bill",
        price: 66.0,
        currency: "MYR",
        daysLeft: 3,
    },
    {
        id: "coway",
        icon: icons.activity,
        name: "Coway",
        price: 135.0,
        currency: "MYR",
        daysLeft: 5,
    },
    {
        id: "time-wifi",
        icon: icons.activity,
        name: "Time Wifi",
        price: 92.0,
        currency: "MYR",
        daysLeft: 8,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "house-asbf",
        icon: icons.home,
        name: "House + ASBF",
        plan: "Loan & Investment",
        category: "Housing",
        status: "active",
        price: 1500.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#e8def8",
    },
    {
        id: "saving",
        icon: icons.wallet,
        name: "Personal Savings",
        plan: "Emergency / General",
        category: "Savings",
        status: "active",
        price: 3000.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#b8e8d0",
    },
    {
        id: "car",
        icon: icons.activity,
        name: "Car Loan",
        plan: "Auto Financing",
        category: "Transport",
        status: "active",
        price: 550.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#f5c542",
    },
    {
        id: "babysitter",
        icon: icons.activity,
        name: "Babysitter",
        plan: "Childcare",
        category: "Family",
        status: "active",
        price: 460.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#ffcdd2",
    },
    {
        id: "wife",
        icon: icons.wallet,
        name: "Wife Allowance",
        plan: "350 + 100",
        category: "Family",
        status: "active",
        price: 450.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#f8bbd0",
    },
    {
        id: "spaylater",
        icon: icons.wallet,
        name: "Shopee SPayLater",
        plan: "Installments",
        category: "Shopping",
        status: "active",
        price: 351.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#ffcc80",
    },
    {
        id: "maintenance-water",
        icon: icons.home,
        name: "Maintenance + Water",
        plan: "Utilities",
        category: "Housing",
        status: "active",
        price: 250.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#b3e5fc",
    },
    {
        id: "coway",
        icon: icons.activity,
        name: "Coway",
        plan: "Water Purifier",
        category: "Utilities",
        status: "active",
        price: 135.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#b2ebf2",
    },
    {
        id: "tax-assessment",
        icon: icons.home,
        name: "Tax Assessment Pay@KL",
        plan: "Cukai Pintu",
        category: "Housing",
        status: "active",
        price: 110.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#d1c4e9",
    },
    {
        id: "tabung-haji",
        icon: icons.wallet,
        name: "Tabung Haji Adra",
        plan: "Child Savings",
        category: "Savings",
        status: "active",
        price: 100.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#c8e6c9",
    },
    {
        id: "time-wifi",
        icon: icons.activity,
        name: "Time Internet",
        plan: "Home Broadband",
        category: "Utilities",
        status: "active",
        price: 92.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#ffecb3",
    },
    {
        id: "tnb",
        icon: icons.activity,
        name: "TNB",
        plan: "Electricity",
        category: "Utilities",
        status: "active",
        price: 66.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#fff9c4",
    },
    {
        id: "asnb",
        icon: icons.wallet,
        name: "ASNB",
        plan: "Investment",
        category: "Savings",
        status: "active",
        price: 50.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#dcedc8",
    },
    {
        id: "icloud",
        icon: icons.dropbox, // Used dropbox as a cloud fallback icon
        name: "Apple iCloud",
        plan: "Cloud Storage",
        category: "Subscriptions",
        status: "active",
        price: 44.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#bbdefb",
    },
    {
        id: "umobile",
        icon: icons.activity,
        name: "Umobile",
        plan: "Mobile Plan",
        category: "Utilities",
        status: "active",
        price: 40.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#ffe0b2",
    },
    {
        id: "wash-car",
        icon: icons.activity,
        name: "Wash Car",
        plan: "Maintenance",
        category: "Transport",
        status: "active",
        price: 20.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#cfd8dc",
    },
    {
        id: "atome",
        icon: icons.wallet,
        name: "Atome",
        plan: "Buy Now Pay Later",
        category: "Shopping",
        status: "active",
        price: 14.0,
        currency: "MYR",
        billing: "Monthly",
        color: "#f8bbd0",
    },
];